@startuml



component DataStore

interface DataStoreAPI
DataStore - DataStoreAPI : provide

component NetworkNode
DataStoreAPI <. NetworkNode : require

interface NodeDiscovery
NetworkNode -- NodeDiscovery: provide
NodeDiscovery <.. NetworkNode : require

interface NodeAPI
NetworkNode - NodeAPI : provide

component Client
NodeAPI <. Client : require

@enduml
